### ISSUE TITLE
<!-- build:remove --> doesn't work on a particular file

### ISSUE THREAD

**Issue by goodpixels** [dciccale/grunt-processhtml#68] opened 2015-02-03 10:51 UTC
hi. im using the plugin to generate *.cshtml templates for a .NET project.

everything gets processed nicely, except for `build:remove` blocks - in one particular file.

here's my task:

```
processhtml: {

	options: {

		// Use the following file for string replacement inside HTML files

		data: {

			results:		grunt.file.readJSON( 'razor_src/results.json' ),
			home:			grunt.file.readJSON( 'razor_src/home.json' ),
			dashboard:		grunt.file.readJSON( 'razor_src/dashboard.json' ),

		}

	},

	razor: {

		files: {

			'razor_templates/Home/Index.cshtml':							[ 'home.php' ],					
			'razor_templates/Home/_Dashboard.cshtml':						[ 'dashboard.php' ],
			'razor_templates/Results/Index.cshtml':							[ 'results.php' ],

		}

	},

},
```

and here's the source code for the file in question:

```
<!-- build:remove -->remove me<!-- /build -->

<!-- build:js production.js --><script src="development.js"><script><!-- /build -->
```

here's the result:

```
<!-- build:remove -->remove me<!-- /build -->

<script src="production.js"></script>
```

**Comment by goodpixels** [comment] 2015-02-03 10:57
I can confirm this is an issue with 0.3.7. Installed 0.3.6 and it works just fine.

**Comment by dciccale** [comment] 2015-04-05 11:24
The remove doesn't work inline

try this:

```html
<!-- build:remove -->
remove me
<!-- /build -->
```

**Comment by goodpixels** [comment] 2015-05-07 21:54
that doesn't solve anything. like i said earlier: the old version worked fine, the new one doesn't. this is clearly a bug that needs to be fixed.

**Comment by dciccale** [comment] 2015-05-07 22:31
I am not able to reproduce the bug tried with this example and is working:

(in both version 0.37 and 0.36) i am not sure about the cause of your issue, maybe if you share a bigger piece of your file to check that the parser is not failing would be better.

and please, try this example out and tell me your result

`file.html`
```html
<!doctype html>
  <html>
    <head>
      <title>demo</title>
    </head>

    <body>

      <!-- build:remove -->remove me<!-- /build -->

      <!-- build:js production.js --><script src="development.js"></script><!-- /build -->
    </body>
</html>
```

`Gruntfile.js`
```javascript
module.exports = function (grunt) {
  grunt.initConfig({
    processhtml: {
      all: {
        files: {
          'processed.html': ['file.html']
        }
      }
    }
  });

  grunt.loadNpmTasks('grunt-processhtml');
  grunt.registerTask('default', ['processhtml']);
};
```

```bash
$ grunt
```

and the result in `processed.html`

```html
<!doctype html>
  <html>
    <head>
      <title>demo</title>
      <script src="demo.js"></script>
    </head>

    <body>

      <script src="production.js"></script>
    </body>
</html>
```

**Comment by goodpixels** [comment] 2015-05-08 14:46
i just played with 0.3.7 and your example works fine, but mine still doesn't. i even stripped everything down to this:

```
<!-- build:remove -->remove me<!-- /build -->
```

and it's still there. i think it's got something to do with line breaks?

FYI 0.3.6 works fine on the same example.

**Comment by gguillemot** [comment] 2015-06-10 14:15
I confirm that changing line delimiters from LF (unix) to CRLF (windows) fix this issue.

**Comment by dciccale** [comment] 2015-06-10 14:31
ok will check what was changed regarding the EOF and fix it thanks Gildas

**Comment by dciccale** [comment] 2015-06-17 07:54
i have tried with both LF and CRLF, even mixed line endings and all of the examples works with both 0.3.7 and 0.3.6 I really don't know what else to try man. please check you file format, line endings, or just create a new file and try it.
what system are you using?

**Comment by dciccale** [comment] 2015-06-17 07:56
it is really wierd that from 18k downloads/month since a year, this is the only case

**Comment by bdoooh** [comment] 2015-06-20 18:55
I am having this exact same problem. Works fine though in 0.3.6. I just tested 0.3.8, same issue.

**Comment by bdoooh** [comment] 2015-06-20 19:04
So I grabbed `0.3.8` and downgraded `htmlprocessor` to `0.1.9` and that seemed to fix the issue.

**Comment by dciccale** [comment] 2015-06-21 10:27
interesting, thanks for the feedback, will continue looking for this to be
solved

**Comment by krismeister** [comment] 2015-06-23 17:22
I did experience something similar to this. The HTML was being pre-processed by https://github.com/Automattic/juice which possible changed something in the character encoding. I don't have much experience dealing with encoding issues or else I'd help troubleshoot further.

Switching to htmlprocessor 3.6 solved my issue above.

**Comment by dciccale** [comment] 2015-07-06 08:55
looks like this is breaking `htmlprocessor` `0.1.10` https://github.com/dciccale/node-htmlprocessor/commit/3cf63b3fdd751ba63669ca3180684a0f77463892

need further review to fix that back again without breaking the other changes introduced.

**Comment by LeleDev** [comment] 2015-07-13 15:19
+1 Eagerly waiting for a fix

**Comment by dciccale** [comment] 2015-08-03 10:28
i have been looking deep into this. i am not sure on how to approach it because the plugin is already handling all different types of line endings and I have tried both, even mixed. I am not sure what is the issue with the files you have. if one of you could send me one of those files that are failing (untouched) via email to dciccale@gmail.com it would be helpful.

**Comment by dciccale** [comment] 2015-08-05 00:09
can someone download this version of the processor and try to process the html file with that one? https://github.com/dciccale/node-htmlprocessor is not published to npm yet so you'll have to get it directly from the repo url, or download a zip

**Comment by dciccale** [comment] 2015-08-26 20:02
ping

there is a new version of the processor here https://github.com/dciccale/node-htmlprocessor please if someone could try it would be great to see if the issue was fixed correctly

**Comment by dciccale** [comment] 2015-09-13 09:19
@bdoooh could you try it?

**Comment by bdoooh** [comment] 2015-09-16 13:11
@dciccale hmm unless something has changed on my end, looks like using `"htmlprocessor": "^0.1.10"` in the dependencies works now with removing.

**Comment by dciccale** [comment] 2015-09-16 15:02
nothing has changed so must be your code

**Comment by bdoooh** [comment] 2015-09-16 15:04
@dciccale what's weird is I see the new version but when I delete the plugin from `node_modules` & run `npm install htmlprocessor --save` it just pulls in `0.1.10`.

**Comment by dciccale** [comment] 2015-09-16 15:08
yes because the new version is not published in npm.

you will have to download a zip from here https://github.com/dciccale/node-htmlprocessor/archive/master.zip

exctract it in node_modules/htmlprocessor and run "npm install" in that folder. the you will have latest htmlprocessor

**Comment by dciccale** [comment] 2015-09-16 15:09
in any case, if you are not experiencing the issue anymore, this will not give us any feedback hope the other guys can join @krismeister @LeleDev @gguillemot @goodpixels

**Comment by bdoooh** [comment] 2015-09-16 15:27
Alright @dciccale I was finally able to reproduce. Dropping in the new one seemed to fix the problem! Let's get it moved into the npm registry!

**Comment by dciccale** [comment] 2015-09-16 16:36
really? sounds great thanks a lot @bdoooh !

i will wait couple of days to get more feedback. if nothing moves here anymore i will publish on saturday and close the issue.

thx again

**Comment by bdoooh** [comment] 2015-09-16 16:48
Yup! My process to test was.. 

1. Remove `grunt-processhtml` from `node_modules`
2. Run `npm install grunt-processhtml`
3. Run my grunt build, notice that my remove tag isn't removing the contents
4. Grab the `master.zip` & unzipped it into `node_modules/grunt-processhtml/node_modules/` and ran `npm install` within that.
5. Re-run my grunt build & that remove tag worked!

**Comment by dciccale** [comment] 2015-09-16 16:49
oh perfect, yeahp. thanks for sharing the process, that was exactly what you needed to do.

**Comment by johnv-git** [comment] 2015-10-15 02:22
Just ran into this one.  Embedded CR (aka ^M) in the html file silently prevents grunt-processhtml from doing replacements.

It'll even successfully detect that the source file for inlining doesn't exist.  But then silently fails to perform any substitutions.

**Comment by johnv-git** [comment] 2015-10-15 02:29
In case you need a test case.  Replace ^M with Ctrl-V/Ctrl-M in vi or your equivalent text based editor.

```
<html>
<p>MS-DOS line endings</p>
<!-- build:remove -->
  <p>do not</p>
<!-- /build -->
<p>make me happy.</p>^M
</html>
```

**Comment by dciccale** [comment] 2015-10-15 07:28
good example xD

will fix it asap

**Comment by dciccale** [comment] 2015-10-15 08:31
ok, what i see is that the linefeed is saved to be `\r\n` (because of the ^M) so later when the `remove` block is called, is trying to split the original content (which has `\n` and `\r\n`) with the string which has only `\r\n` in it (this is normalized in the getBlocks) method.

this is the content
```
<html>\n<p>MS-DOS line endings</p>\n<!-- build:remove -->\n  <p>do not</p>\n<!-- /build -->\n<p>make me happy.</p>\r\n</html>\n
```

this is the content used to split, but will not work since it doesn't match line endings. and the replacement never takes place.

```
<!-- build:remove -->\r\n  <p>do not</p>\r\n<!-- /build -->
```

one possible solution is normalizing always to 1 lineending. however i think this whole logic for detecting lineending and trying to keep it is because well obvious reasons to output the file with same lineendings it came.

i will try to solve it while keeping line endings, but if i cannot well.. maybe normalizing everything to `\n` would be a choice

**Comment by dciccale** [comment] 2015-10-15 09:23
working with mixed linefeeds is crazy. the solution is normalizing everything to `\n` for the output file. windows guys, would be this an issue?

any thoughts @johnv-git ?

**Comment by deimyts** [comment] 2016-02-10 15:39
Just ran into this issue on a mac. I can't speak for whether `\n` would cause issues with windows, but I wonder if there is a way to normalize the output using node's [os.EOL](https://nodejs.org/api/os.html#os_os_eol)?

**Comment by dciccale** [comment] 2016-02-10 15:43
the issue is that if a file comes with mixed end of line, os.EOL will only match the one of the OS, but not others..

anyway I think that the processed file should be normalized into `\n` without caring for what it had in the first place.

will put this in the next release of [node-htmlprocessor](https://github.com/dciccale/node-htmlprocessor)

**Comment by deimyts** [comment] 2016-02-11 14:42
Right, but if a file has mixed line endings in the first place, it's probably by accident.
The possible use for preserving a file with mixed line endings (I'm not sure what it would be, but there might be one)  seems way smaller than the use for saving it with line endings that will match the rest of your files.
So if you're already replacing all line endings with `\n`, why not replace them with `os.EOL` instead, so that it will automatically normalize to `\n` on mac and `\r\n` on windows, still without caring what it had in the first place?

**Comment by dciccale** [comment] 2016-02-11 18:39
makes sense yeah

**Comment by dciccale** [comment] 2016-02-20 12:11
I've done just that https://github.com/dciccale/node-htmlprocessor/blob/master/lib/htmlprocessor.js#L108-L109

also added more tests with mixed eol

**Closed** 2016-02-20 12:27 UTC
Labels: bug
